# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d203f84a1858d66dd31d8f07b9fd507f22579507b9563d5ba03ad5e69282e37e0bcf13c1066e7d5e7ad7591a1c48f043e7ef80e2741fc5ce75ca5723ccaf4dc5

test:
  secret_key_base: 6232d5f6f18d19063d6ea7d86a0de3a6e4f01dd3632c105ca2dc90de48f89281f72bd712120eccca33074f702490883f658831ff3c29e6c7211d14c1282703db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
